# Template Konfigurasi Nginx untuk React (Vite) + Backend Reverse Proxy 
# Simpan/Copy blok ini ke: /etc/nginx/sites-available/napaslega
# Lalu link ke sites-enabled dan restart nginx

server {
    listen 80;
    
    # Ganti dengan IP Publik EC2 mu atau Nama Domain jika ada
    server_name IP_PUBLIC_EC2_ANDA; 

    # Arahkan ke jalur Absolut folder hasil `npm run build` (folder /dist) yang kamu taruh di server EC2
    root /var/www/napaslega/fe/dist;
    index index.html index.htm;

    # 1. Aturan Dasar React SPA (Single Page Application)
    # Tujuan: Mengembalikan setiap URL React-Router-Dom tetap ke index.html saat direfresh
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Aturan Reverse Proxy Server Node.js Docker
    # Jika react memanggil `/api/xxx`, tembakkan / terususkan ke Port 5000 lokal Docker di dalam EC2
    location /api/ {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
