name: Deploy Frontend React to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Eksekusi Build di Dalam EC2 Server
        env:
          HOST: ${{ secrets.IP_EC2 }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$HOST << 'EOF'
            cd /var/www/NapasLega
            
            git pull origin main
            
            cd fe
            
            sudo chown -R ubuntu:ubuntu /var/www/NapasLega/fe
            
            rm -rf dist
            
            npm install
            npm run build
            
            sudo chown -R www-data:www-data /var/www/NapasLega/fe/dist
            
            sudo systemctl restart nginx
          EOF